cam_id: 0
delay_reset: 1
display: 1
img:
  perspective:
    pts1:
    - - 0
      - 0
    - - 0
      - 0
    - - 0
      - 0
    - - 0
      - 0
    pts2:
    - - 0
      - 0
    - - 0
      - 0
    - - 0
      - 0
    - - 0
      - 0
pole:
  decal_blue: -5
  decal_yellow: 10
  height: 150
robots:
  blue_ar_height: 43
  blue_id_range:
  - 1
  - 5
  yellow_ar_height: 43
  yellow_id_range:
  - 6
  - 10
