cam_id: 0
delay_reset: 1
display: 1
img:
  perspective:
    pts1:
    - - 1326.0
      - 379.25
    - - 788.25
      - 388.75
    - - 1469.5
      - 718.5
    - - 753.0
      - 742.75
    pts2:
    - - 1225.800048828125
      - 270.0
    - - 394.20001220703125
      - 270.0
    - - 1225.800048828125
      - 810.0
    - - 394.20001220703125
      - 810.0
logger: INFO
pole:
  decal: 10 # in cm. positive : left, negative : right
  height: 160 # in cm
robots:
  blue_ar_height: 44 # in cm
  blue_id_range:
  - 51
  - 70
  yellow_ar_height: 50 # in cm
  yellow_id_range:
  - 71
  - 90
