img:
  name: imgboard8.jpg
  perspective:
    pts1:
    - - 0
      - 0
    - - 0
      - 0
    - - 0
      - 0
    - - 0
      - 0
    pts2:
    - - 0
      - 0
    - - 0
      - 0
    - - 0
      - 0
    - - 0
      - 0
pole:
  decal: 0.0
  height: 100.0
robots:
  enemy_id: 5
  friendly_id: 1
  radius: 191
